### ISSUE TITLE
Write a develop document

### ISSUE THREAD

**Issue by sanjayankur31** [fzenke/auryn#14]
Since the project has started to see contributions from people, maybe a style document is in order. I saw you fixed the tabs and so on in the AdEx. Maybe a quick wiki page or addition to readme on what style we should follow before we open pull requests? 

I use vim and generally only use spaces instead of tabs for example, but it's quite simple to set up project specific styles once we know what upstream(you) require :)

**Comment by fzenke** [comment]
Good idea. I will think of something.

**Comment by fzenke** [comment]
http://www.fzenke.net/auryn/doku.php?id=manual:coding_style_guide

What do you think?

**Comment by sanjayankur31** [comment]
Seems good! As more people contribute, the document will evolve by itself :) Closing this ticket.

Thanks.
