### ISSUE TITLE
There was a problem compiling when I used Aruyn

### ISSUE THREAD

**Issue by Craw-B** [fzenke/auryn#38]
Which boost library version matches Aruyn。I used 1.75，1.80 ，but filed。There was some questions with openmpi.

**Comment by Craw-B** [comment]
The boost library is installed with source code. The installed version is 1.75. The mpi uses version 3.3.2. It is also installed with source code.
![image](https://user-images.githubusercontent.com/82355890/195005737-7ddb969d-4d71-4a70-a2f7-94d6ce15ed03.png)

**Comment by Craw-B** [comment]
I have a small problem. On the auryn simulator, how to allocate neurons in each process? I can't find the corresponding code

**Comment by fzenke** [comment]
I am not sure I understand the questions. Neurons are usually distributed in a round robin manner across processes. How this is done is implemented in the abstract base class `SpikingGroup`. Hope that's what you're asking.

**Comment by Craw-B** [comment]
I will continue to try, thank you for your reply
