### ISSUE TITLE
About Poisson Random Number

### ISSUE THREAD

**Issue by Craw-B** [fzenke/auryn#40]
Why does the Poisson random number generated by aruyn conform to the Poisson distribution, and how to prove it. In the paper, I don't understand, and the code doesn't know the reason for doing so. Whether there is a corresponding mathematical method to prove it.

**Comment by fzenke** [comment]
Thanks for the question. The waiting times are exponential for a Poisson distribution.  I quote Wikipedia "If for every t > 0 the number of arrivals in the time interval [0, t] follows the Poisson distribution with mean λt, then the sequence of inter-arrival times are independent and identically distributed exponential random variables [...]." https://en.wikipedia.org/wiki/Poisson_distribution You should be able to find many proofs online. I hope that helps.
