### ISSUE TITLE
Provide a NeuroML/Lems interface

### ISSUE THREAD

**Issue by sanjayankur31** [fzenke/auryn#5]
We had a visit from @pgleeson yesterday. He runs the Open Source Brain project (http://www.opensourcebrain.org/ and https://github.com/OpenSourceBrain). Since I'm using auryn, we talked about how we could make include auryn with the other models that OSB supports. 

I haven't looked into the details yet, but I thought I'd open this ticket to start a discussion.

**Comment by pgleeson** [comment]
@sanjayankur31, I haven't forgotten about this. It's on a long list of TODOs, and slowly working its way up...

**Comment by pgleeson** [comment]
> @sanjayankur31, I haven't forgotten about this. It's on a long list of TODOs, and slowly working its way up...

I guess I had forgotten about it... 

If this is something you are interested in down the line @fzenke, please get in contact with me or @sanjayankur31. It might make a nice student (summer) project for someone with some Python & C++ experience.
